export const FETCH_TASKS_REQUEST = 'FETCH_TASKS_REQUEST'
export const FETCH_TASKS_SUCCESS = 'FETCH_TASKS_SUCCESS'
export const FETCH_TASKS_FAILURE = 'FETCH_TASKS_FAILURE'

export const TOGGLE_TASK_REQUEST = 'TOGGLE_TASK_REQUEST'
export const TOGGLE_TASK_SUCCESS = 'TOGGLE_TASK_SUCCESS'
export const TOGGLE_TASK_FAILURE = 'TOGGLE_TASK_FAILURE'

export const CREATE_TASK_REQUEST = 'CREATE_TASK_REQUEST'
export const CREATE_TASK_SUCCESS = 'CREATE_TASK_SUCCESS'
export const CREATE_TASK_FAILURE = 'CREATE_TASK_FAILURE'

export const UPDATE_TASK_REQUEST = 'UPDATE_TASK_REQUEST'
export const UPDATE_TASK_SUCCESS = 'UPDATE_TASK_SUCCESS'
export const UPDATE_TASK_FAILURE = 'UPDATE_TASK_FAILURE'

export const DELETE_TASK_REQUEST = 'DELETE_TASK_REQUEST'
export const DELETE_TASK_SUCCESS = 'DELETE_TASK_SUCCESS'
export const DELETE_TASK_FAILURE = 'DELETE_TASK_FAILURE'

export const SWITCH_TAB = 'SWITCH_TAB'

export const ALL_TASKS = 'All Tasks'
export const ACTIVE_TASKS = 'Active Tasks'
export const DONE_TASKS = 'Done Tasks'
export const TABS = [ALL_TASKS, ACTIVE_TASKS, DONE_TASKS]
